Use true when setting 'trust proxy' on express
allegro/turnilo pull request #668
Opened 2020-10-20 18:26 UTC by milimetric

According to docs, 'trust proxy' can be set to one of these values:
http://expressjs.com/en/guide/behind-proxies.html

If it is set to 1 instead of true, the default behavior is invoked, and
that's to not trust anything from the XFF header.  So the req.ip value
is set to, unpredictably, the last ip in the header.  I followed this
logic down through express -> proxy-addr -> forwarded.  In a simple case
of an XFF header with one ip, everything appears to work normally, but
if XFF looks like this:

123.234.1.1, 10.1.1.10, 234.123.0.1

Then if 'trust proxy' is set to 1, req.ip will be 234.123.0.1 instead of
the expected 123.234.1.1.  When setting it to true instead, the correct
trust function is compiled and used in the call chain mentioned above.

2020-10-20 18:46 UTC, adrianmroz commented
@mkuthan @fpoon what you think? Sounds reasonable for me but I have very limited network experience. If it is more complicated, maybe we should allow to define this value in config?

2020-10-20 20:32 UTC, milimetric commented
(I'm happy to make it work any way yall think is best long term)

2020-10-21 09:25 UTC, fpoon requested changes
Nice one, but please, update the out-dated comment :)

2020-10-21 09:25 UTC, fpoon commented on src/server/app.ts
> +  app.set("trust proxy", true); // trust first proxy
Could you please update this comment? Express will no longer trust only the first proxy.

2020-10-21 14:41 UTC, adrianmroz commented
I think we can merge it into next beta. If it breaks for someone, we could revert and provide more options for `trustProxy`.

2020-10-21 14:44 UTC, milimetric commented
As far as breaking, there are three scenarios:

* no XFF, change is no-op
* XFF with one entry, change is no-op
* XFF with multiple entries, breaks if relying on the req.ip but I didn't find anything like that in the code

I'm game to add more options to the config and map it properly to express's `set('trust proxy'...`, just ping me.

2020-10-21 15:33 UTC, merged

2020-10-21 16:27 UTC, mkuthan commented
> @mkuthan @fpoon what you think? Sounds reasonable for me but I have very limited network experience. If it is more complicated, maybe we should allow to define this value in config?

Keep it simple, „true” instead of „1” makes more sense for me. We trust or no :)