@exherb allow new numbrojs format
allegro/turnilo pull request #722
Opened 2021-03-16 06:58 UTC by exherb

2021-03-17 13:42 UTC, exherb commented
please review~

2021-03-25 15:28 UTC, adrianmroz-allegro commented
In future, please describe your change to help us in review process.

Even more, it would be better to first discuss feature requests with Turnilo team so we can help you with design and answer quickly how we feel about such feature.

We didn't update number format yet, because we think that first we need to figure out how UI should look like. Expecting that users will write magic strings (like now) wasn't that great idea but I think that expecting them to write valid JSON object is even worse. 

We are open to the idea that admin could define in config default formatting as object.

2021-03-25 15:49 UTC, adrianmroz-allegro requested changes

2021-03-25 15:49 UTC, adrianmroz-allegro commented on src/client/components/series-menu/format-picker.tsx
> +function readFormat(format: string, measureFormat: {} | string): SeriesFormat {
Use `FormatString` type instead of inlining it. I know that numbro types are quite poor, but let's cover them with good names.

2021-03-25 15:49 UTC, adrianmroz-allegro commented on src/client/components/series-menu/format-picker.tsx
> +      return typeof measureFormat === "string" ? measureFormat : JSON.stringify(measureFormat);
That's some tricky operation that's repeated multiple times. Maybe some util?

2021-03-25 15:49 UTC, adrianmroz-allegro commented on src/client/components/series-menu/format-picker.tsx
> +      return typeof format.value === "string" ? format.value : JSON.stringify(format.value);
Why we stringily custom format? Do we allow user to insert json object in input? If so, we should handle reading in `readFormat`

2021-03-25 15:49 UTC, adrianmroz-allegro commented on src/common/models/measure/measure.ts
> +  format?: {} | string;
Measure probably should have format as discriminated union, so we don't need to use `typeof` in runtime

2021-03-25 15:49 UTC, adrianmroz-allegro commented on src/common/models/measure/measure.ts
> +  format?: {} | string;
Object is not a primitive and thus will not be serialised-deserialised properly. You should add test for this case

2021-03-27 07:37 UTC, closed without merging